version: 0.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
        name: one
        command: echo "step one"
      - run:
        name: two
        command: echo "step two"
      - run:
        name: mail
        command: echo "mail is "$MAIL
